## Download and Clean Census Data by CT

In [16]:
import pandas as pd
import numpy as np

In [17]:
#Clean CT Data Table
ct = pd.read_csv("data/census/CT/ct_census.csv")

ct = ct.rename(columns = 
              {'v_CA21_560: Median total income in 2020 among recipients ($)':"Median_Income",
               'v_CA21_4410: Immigrants':"Immigrant#",
               "v_CA21_4875: Total visible minority population":"VM#",
               "v_CA21_1025: In low income based on the Low-income measure, after tax (LIM-AT)":"LIncome#",
               'Population ':"Population"
              })

ct.columns = ct.columns.str.replace(" ", "")

In [18]:
#Calculate immigrant and visible miniority percentages
ct["Immigrant%"] = ct.apply(lambda x: x["Immigrant#"]/x["Population"]*100, axis=1)
ct["Visible_Minority%"] = ct.apply(lambda x: x["VM#"]/x["Population"]*100, axis =1)
ct["Low-Income%"]=ct.apply(lambda x:x["LIncome#"]/x["Population"]*100, axis=1)

#Calculate population density, immigrant density, visible minority density
ct["Population_Density"] = ct.apply(lambda x: x["Population"]/x["Area(sqkm)"], axis =1)
ct["Immigrant_Density"] = ct.apply(lambda x: x["Immigrant#"]/x["Area(sqkm)"], axis =1)
ct["VM_Density"]= ct.apply(lambda x: x["VM#"]/x["Area(sqkm)"], axis =1)

In [19]:
ct

,Unnamed:0,GeoUID,Type,RegionName,Area(sqkm),Population,Dwellings,Households,Median_Income,Immigrant#,VM#,LIncome#,Immigrant%,Visible_Minority%,Low-Income%,Population_Density,Immigrant_Density,VM_Density
0,0,5350001.00,CT,1.00,6.8192,599,253,235,57200.0,140.0,185.0,55,23.372287,30.884808,9.181970,87.840216,20.530267,27.129282
1,1,5350002.00,CT,2.00,3.3926,604,294,284,40800.0,125.0,10.0,70,20.695364,1.655629,11.589404,178.034546,36.844898,2.947592
2,2,5350003.00,CT,3.00,0.9455,457,279,265,59200.0,215.0,275.0,60,47.045952,60.175055,13.129103,483.342147,227.392914,290.851401
3,3,5350004.00,CT,4.00,0.3404,6306,3620,3276,33200.0,2600.0,2985.0,1365,41.230574,47.335871,21.646051,18525.264395,7638.072855,8769.095182
4,4,5350005.00,CT,5.00,0.3764,6957,4235,3720,40000.0,2525.0,3210.0,1330,36.294380,46.140578,19.117436,18482.996812,6708.289054,8528.161530
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
580,580,5350378.26,CT,378.26,1.6267,4867,1234,1213,34400.0,3100.0,4820.0,235,63.694268,99.034313,4.828436,2991.946886,1905.698654,2963.054036
581,581,5350378.27,CT,378.27,19.9096,5547,1565,1526,36000.0,3345.0,5255.0,275,60.302866,94.735893,4.957635,278.609314,168.009402,263.943022
582,582,5350378.28,CT,378.28,2.2278,6946,2017,1931,34400.0,4085.0,6545.0,500,58.810826,94.226893,7.198388,3117.874136,1833.647545,2937.875931
583,583,5350802.01,CT,802.01,2.1742,4011,1328,1303,47200.0,1695.0,2295.0,195,42.258788,57.217651,4.861631,1844.816484,779.597093,1055.560666
584,584,5350802.02,CT,802.02,2.2570,5373,1830,1799,52800.0,1850.0,2470.0,215,34.431416,45.970594,4.001489,2380.593708,819.672131,1094.373062

In [20]:
ct["GeoUID"] = ct["GeoUID"].apply(lambda x:"{:.2f}".format(x))
ct

,Unnamed:0,GeoUID,Type,RegionName,Area(sqkm),Population,Dwellings,Households,Median_Income,Immigrant#,VM#,LIncome#,Immigrant%,Visible_Minority%,Low-Income%,Population_Density,Immigrant_Density,VM_Density
0,0,5350001.00,CT,1.00,6.8192,599,253,235,57200.0,140.0,185.0,55,23.372287,30.884808,9.181970,87.840216,20.530267,27.129282
1,1,5350002.00,CT,2.00,3.3926,604,294,284,40800.0,125.0,10.0,70,20.695364,1.655629,11.589404,178.034546,36.844898,2.947592
2,2,5350003.00,CT,3.00,0.9455,457,279,265,59200.0,215.0,275.0,60,47.045952,60.175055,13.129103,483.342147,227.392914,290.851401
3,3,5350004.00,CT,4.00,0.3404,6306,3620,3276,33200.0,2600.0,2985.0,1365,41.230574,47.335871,21.646051,18525.264395,7638.072855,8769.095182
4,4,5350005.00,CT,5.00,0.3764,6957,4235,3720,40000.0,2525.0,3210.0,1330,36.294380,46.140578,19.117436,18482.996812,6708.289054,8528.161530
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
580,580,5350378.26,CT,378.26,1.6267,4867,1234,1213,34400.0,3100.0,4820.0,235,63.694268,99.034313,4.828436,2991.946886,1905.698654,2963.054036
581,581,5350378.27,CT,378.27,19.9096,5547,1565,1526,36000.0,3345.0,5255.0,275,60.302866,94.735893,4.957635,278.609314,168.009402,263.943022
582,582,5350378.28,CT,378.28,2.2278,6946,2017,1931,34400.0,4085.0,6545.0,500,58.810826,94.226893,7.198388,3117.874136,1833.647545,2937.875931
583,583,5350802.01,CT,802.01,2.1742,4011,1328,1303,47200.0,1695.0,2295.0,195,42.258788,57.217651,4.861631,1844.816484,779.597093,1055.560666
584,584,5350802.02,CT,802.02,2.2570,5373,1830,1799,52800.0,1850.0,2470.0,215,34.431416,45.970594,4.001489,2380.593708,819.672131,1094.373062

In [23]:
ct.fillna(value=0)

,Unnamed:0,GeoUID,Type,RegionName,Area(sqkm),Population,Dwellings,Households,Median_Income,Immigrant#,VM#,LIncome#,Immigrant%,Visible_Minority%,Low-Income%,Population_Density,Immigrant_Density,VM_Density
0,0,5350001.00,CT,1.00,6.8192,599,253,235,57200.0,140.0,185.0,55,23.372287,30.884808,9.181970,87.840216,20.530267,27.129282
1,1,5350002.00,CT,2.00,3.3926,604,294,284,40800.0,125.0,10.0,70,20.695364,1.655629,11.589404,178.034546,36.844898,2.947592
2,2,5350003.00,CT,3.00,0.9455,457,279,265,59200.0,215.0,275.0,60,47.045952,60.175055,13.129103,483.342147,227.392914,290.851401
3,3,5350004.00,CT,4.00,0.3404,6306,3620,3276,33200.0,2600.0,2985.0,1365,41.230574,47.335871,21.646051,18525.264395,7638.072855,8769.095182
4,4,5350005.00,CT,5.00,0.3764,6957,4235,3720,40000.0,2525.0,3210.0,1330,36.294380,46.140578,19.117436,18482.996812,6708.289054,8528.161530
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
580,580,5350378.26,CT,378.26,1.6267,4867,1234,1213,34400.0,3100.0,4820.0,235,63.694268,99.034313,4.828436,2991.946886,1905.698654,2963.054036
581,581,5350378.27,CT,378.27,19.9096,5547,1565,1526,36000.0,3345.0,5255.0,275,60.302866,94.735893,4.957635,278.609314,168.009402,263.943022
582,582,5350378.28,CT,378.28,2.2278,6946,2017,1931,34400.0,4085.0,6545.0,500,58.810826,94.226893,7.198388,3117.874136,1833.647545,2937.875931
583,583,5350802.01,CT,802.01,2.1742,4011,1328,1303,47200.0,1695.0,2295.0,195,42.258788,57.217651,4.861631,1844.816484,779.597093,1055.560666
584,584,5350802.02,CT,802.02,2.2570,5373,1830,1799,52800.0,1850.0,2470.0,215,34.431416,45.970594,4.001489,2380.593708,819.672131,1094.373062

In [24]:
ct.to_csv("data/census/CT/ct_clean.csv")