## Download and Clean Census Data by CT

In [2]:
import pandas as pd
import numpy as np

In [3]:
#Clean CT Data Table
ct = pd.read_csv("data/census/CT/ct_census.csv")

ct = ct.rename(columns = 
              {'v_CA21_560: Median total income in 2020 among recipients ($)':"Median_Income",
               'v_CA21_4410: Immigrants':"Immigrant#",
               "v_CA21_4875: Total visible minority population":"VM#",
               "v_CA21_1025: In low income based on the Low-income measure, after tax (LIM-AT)":"LIncome#",
               'Population ':"Population"
              })

ct.columns = ct.columns.str.replace(" ", "")

In [4]:
#Calculate immigrant and visible miniority percentages
ct["Immigrant%"] = ct.apply(lambda x: x["Immigrant#"]/x["Population"]*100, axis=1)
ct["Visible_Minority%"] = ct.apply(lambda x: x["VM#"]/x["Population"]*100, axis =1)
ct["Low-Income%"]=ct.apply(lambda x:x["LIncome#"]/x["Population"]*100, axis=1)

#Calculate population density, immigrant density, visible minority density
ct["Population_Density"] = ct.apply(lambda x: x["Population"]/x["Area(sqkm)"], axis =1)
ct["Immigrant_Density"] = ct.apply(lambda x: x["Immigrant#"]/x["Area(sqkm)"], axis =1)
ct["VM_Density"]= ct.apply(lambda x: x["VM#"]/x["Area(sqkm)"], axis =1)

In [5]:
ct

,Unnamed:0,GeoUID,Type,RegionName,Area(sqkm),Population,Dwellings,Households,Median_Income,Immigrant#,VM#,LIncome#,Immigrant%,Visible_Minority%,Low-Income%,Population_Density,Immigrant_Density,VM_Density
0,0,5350001.00,CT,1.00,6.8192,599,253,235,57200.0,140.0,185.0,55,23.372287,30.884808,9.181970,87.840216,20.530267,27.129282
1,1,5350002.00,CT,2.00,3.3926,604,294,284,40800.0,125.0,10.0,70,20.695364,1.655629,11.589404,178.034546,36.844898,2.947592
2,2,5350003.00,CT,3.00,0.9455,457,279,265,59200.0,215.0,275.0,60,47.045952,60.175055,13.129103,483.342147,227.392914,290.851401
3,3,5350004.00,CT,4.00,0.3404,6306,3620,3276,33200.0,2600.0,2985.0,1365,41.230574,47.335871,21.646051,18525.264395,7638.072855,8769.095182
4,4,5350005.00,CT,5.00,0.3764,6957,4235,3720,40000.0,2525.0,3210.0,1330,36.294380,46.140578,19.117436,18482.996812,6708.289054,8528.161530
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
580,580,5350378.26,CT,378.26,1.6267,4867,1234,1213,34400.0,3100.0,4820.0,235,63.694268,99.034313,4.828436,2991.946886,1905.698654,2963.054036
581,581,5350378.27,CT,378.27,19.9096,5547,1565,1526,36000.0,3345.0,5255.0,275,60.302866,94.735893,4.957635,278.609314,168.009402,263.943022
582,582,5350378.28,CT,378.28,2.2278,6946,2017,1931,34400.0,4085.0,6545.0,500,58.810826,94.226893,7.198388,3117.874136,1833.647545,2937.875931
583,583,5350802.01,CT,802.01,2.1742,4011,1328,1303,47200.0,1695.0,2295.0,195,42.258788,57.217651,4.861631,1844.816484,779.597093,1055.560666
584,584,5350802.02,CT,802.02,2.2570,5373,1830,1799,52800.0,1850.0,2470.0,215,34.431416,45.970594,4.001489,2380.593708,819.672131,1094.373062

In [6]:
ct["GeoUID"] = ct["GeoUID"].apply(lambda x:"{:.2f}".format(x))
ct

,Unnamed:0,GeoUID,Type,RegionName,Area(sqkm),Population,Dwellings,Households,Median_Income,Immigrant#,VM#,LIncome#,Immigrant%,Visible_Minority%,Low-Income%,Population_Density,Immigrant_Density,VM_Density
0,0,5350001.00,CT,1.00,6.8192,599,253,235,57200.0,140.0,185.0,55,23.372287,30.884808,9.181970,87.840216,20.530267,27.129282
1,1,5350002.00,CT,2.00,3.3926,604,294,284,40800.0,125.0,10.0,70,20.695364,1.655629,11.589404,178.034546,36.844898,2.947592
2,2,5350003.00,CT,3.00,0.9455,457,279,265,59200.0,215.0,275.0,60,47.045952,60.175055,13.129103,483.342147,227.392914,290.851401
3,3,5350004.00,CT,4.00,0.3404,6306,3620,3276,33200.0,2600.0,2985.0,1365,41.230574,47.335871,21.646051,18525.264395,7638.072855,8769.095182
4,4,5350005.00,CT,5.00,0.3764,6957,4235,3720,40000.0,2525.0,3210.0,1330,36.294380,46.140578,19.117436,18482.996812,6708.289054,8528.161530
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
580,580,5350378.26,CT,378.26,1.6267,4867,1234,1213,34400.0,3100.0,4820.0,235,63.694268,99.034313,4.828436,2991.946886,1905.698654,2963.054036
581,581,5350378.27,CT,378.27,19.9096,5547,1565,1526,36000.0,3345.0,5255.0,275,60.302866,94.735893,4.957635,278.609314,168.009402,263.943022
582,582,5350378.28,CT,378.28,2.2278,6946,2017,1931,34400.0,4085.0,6545.0,500,58.810826,94.226893,7.198388,3117.874136,1833.647545,2937.875931
583,583,5350802.01,CT,802.01,2.1742,4011,1328,1303,47200.0,1695.0,2295.0,195,42.258788,57.217651,4.861631,1844.816484,779.597093,1055.560666
584,584,5350802.02,CT,802.02,2.2570,5373,1830,1799,52800.0,1850.0,2470.0,215,34.431416,45.970594,4.001489,2380.593708,819.672131,1094.373062

In [7]:
ct.fillna(value=0)

,Unnamed:0,GeoUID,Type,RegionName,Area(sqkm),Population,Dwellings,Households,Median_Income,Immigrant#,VM#,LIncome#,Immigrant%,Visible_Minority%,Low-Income%,Population_Density,Immigrant_Density,VM_Density
0,0,5350001.00,CT,1.00,6.8192,599,253,235,57200.0,140.0,185.0,55,23.372287,30.884808,9.181970,87.840216,20.530267,27.129282
1,1,5350002.00,CT,2.00,3.3926,604,294,284,40800.0,125.0,10.0,70,20.695364,1.655629,11.589404,178.034546,36.844898,2.947592
2,2,5350003.00,CT,3.00,0.9455,457,279,265,59200.0,215.0,275.0,60,47.045952,60.175055,13.129103,483.342147,227.392914,290.851401
3,3,5350004.00,CT,4.00,0.3404,6306,3620,3276,33200.0,2600.0,2985.0,1365,41.230574,47.335871,21.646051,18525.264395,7638.072855,8769.095182
4,4,5350005.00,CT,5.00,0.3764,6957,4235,3720,40000.0,2525.0,3210.0,1330,36.294380,46.140578,19.117436,18482.996812,6708.289054,8528.161530
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
580,580,5350378.26,CT,378.26,1.6267,4867,1234,1213,34400.0,3100.0,4820.0,235,63.694268,99.034313,4.828436,2991.946886,1905.698654,2963.054036
581,581,5350378.27,CT,378.27,19.9096,5547,1565,1526,36000.0,3345.0,5255.0,275,60.302866,94.735893,4.957635,278.609314,168.009402,263.943022
582,582,5350378.28,CT,378.28,2.2278,6946,2017,1931,34400.0,4085.0,6545.0,500,58.810826,94.226893,7.198388,3117.874136,1833.647545,2937.875931
583,583,5350802.01,CT,802.01,2.1742,4011,1328,1303,47200.0,1695.0,2295.0,195,42.258788,57.217651,4.861631,1844.816484,779.597093,1055.560666
584,584,5350802.02,CT,802.02,2.2570,5373,1830,1799,52800.0,1850.0,2470.0,215,34.431416,45.970594,4.001489,2380.593708,819.672131,1094.373062

In [11]:
ct.to_csv("data/census/CT/ct_clean.csv")

In [10]:
ct.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
Unnamed:0,585.0,292.000000,169.019230,0.000000,146.000000,292.000000,438.000000,584.000000
RegionName,585.0,221.537897,121.284554,1.000000,116.000000,239.000000,316.060000,802.020000
Area(sqkm),585.0,1.078800,1.404554,0.012900,0.453900,0.746900,1.224600,19.909600
Population,585.0,4776.676923,1933.898654,119.000000,3482.000000,4653.000000,5902.000000,13554.000000
Dwellings,585.0,2142.287179,1217.011101,1.000000,1411.000000,1921.000000,2546.000000,8969.000000
Households,585.0,1984.430769,1060.128634,0.000000,1321.000000,1802.000000,2381.000000,7893.000000
Median_Income,583.0,42285.420240,12003.641062,23800.000000,33200.000000,38400.000000,49000.000000,87000.000000
Immigrant#,583.0,2206.106346,1157.223772,120.000000,1315.000000,2120.000000,2942.500000,6585.000000
VM#,583.0,2636.955403,1693.211746,10.000000,1257.500000,2365.000000,3677.500000,9055.000000
LIncome#,585.0,621.965812,417.058230,0.000000,320.000000,530.000000,830.000000,2930.000000
Immigrant%,583.0,45.025573,14.117257,14.274062,33.470801,46.023397,56.661949,75.983146
Visible_Minority%,583.0,52.956080,23.925575,1.655629,31.564600,52.319310,74.443579,99.034313
Low-Income%,585.0,12.613749,5.785655,0.000000,8.541794,11.431283,16.062063,37.171351
Population_Density,585.0,8446.460672,9191.954493,87.840216,3389.762995,5740.864901,9244.946492,77545.327755
Immigrant_Density,583.0,3866.584150,4746.172848,20.530267,1458.727336,2432.762836,4091.576429,45920.502092
VM_Density,583.0,4690.820345,6392.131335,2.947592,1546.019376,2642.949734,5085.046909,63145.048815